### ISSUE TITLE
Which Dataset File to Download?

### ISSUE THREAD

**Issue by anujdutt9** [FangGet/ORB_SLAM2_Android#11]
Hi, 
Can anyone guide me as to which dataset file I need to download and how to load that into the app?
Thanks

**Comment by neocultureT** [comment]
hello!
Did you solved this problem?I also want to know how to choose the dataset file and load into this app.
if you solved this problem,can you tell me how to solve it?
Thank you!

**Comment by IamMegatron2025** [comment]
ORBvoc.bin and camera.yaml
